add_newline = true
format = "$directory$git_branch$git_state$git_status$python$node\n$character"

[character]
success_symbol = "❯"
error_symbol = "❯"

[directory]
truncation_length = 3
truncate_to_repo = true

[git_branch]
format = " on [$symbol$branch]($style) "

[python]
format = " [ $virtualenv]($style)"

[nodejs]
format = " [ $version]($style)"
